### ISSUE TITLE
Image export function is not available

### ISSUE THREAD

**Issue by yiios** [riwigefi/light-gpt#25]
![bf8848ad-115f-486d-b832-1fcc2de0a370](https://user-images.githubusercontent.com/18002671/225002820-0b1cb688-7461-49aa-81a8-a8efdccc14bb.png)

**Comment by riwigefi** [comment]
The error occurred because when Canvas is drawing an element with a width of 0px and a height of 0px, the `drawmImage()` function throws an error. This was caused by a style modification, which has now been fixed.

I have now updated with a new feature that supports the "New Chat" function. The historical conversation data of the topic will be stored in the IndexedDB database, as this is a storage method with relatively large capacity on the browser-side. We hope that you will find it more comfortable to use.

**Comment by yiios** [comment]
> 
cool
